---
- name: Check blkid for each label
  command: blkid -L {{ item }}
  register: _label_check
  loop: "{{ input_list | default([]) | map(attribute='label') | reject('equalto', '') | list }}"
  failed_when: false
  changed_when: false
  become: true

- name: Collect missing labels
  set_fact:
    missing_labels: "{{ _label_check.results | rejectattr('rc', 'equalto', 0) | map(attribute='item') | list }}"

- name: Fail if any labels are missing
  fail:
    msg: 'Missing {{ label_type }} devices with labels: {{ missing_labels }}'
  when: missing_labels | length > 0
