---
- name: Manage Debian-based PKGs
  block:
    - name: Remove unnecessary PKGs
      apt:
        name: '{{ PKGS_DEBIAN_REMOVAL_LIST }}'
        state: absent
        purge: true
        autoremove: true
      become: true

    - name: Update Debian-based system
      apt:
        name: '*'
        state: latest
        update_cache: true
      become: true

    - name: Install necessary PKGs
      apt:
        name: '{{ PKGS_DEBIAN_INSTALLATION_LIST }}'
        state: latest
        update_cache: true
      become: true

    - name: Autoremove unused pkgs
      apt:
        autoremove: true
        purge: true
      become: true

    - name: Clean APT cache
      apt:
        autoclean: true
      become: true

  when: ansible_os_family == "Debian"

- name: Manage RHEL-based PKGs
  block:
    - name: Install python3-libdnf5
      shell: rpm -q python3-libdnf5 || dnf install -y python3-libdnf5
      changed_when: false
      become: true
      when:
        - ansible_distribution == "Fedora"
        - ansible_distribution_major_version | int >= 41

    - name: Install python3-libdnf
      shell: rpm -q python3-libdnf || dnf install -y python3-libdnf
      changed_when: false
      become: true
      when: ansible_distribution != "Fedora"

    - name: Remove unnecessary PKGs
      dnf:
        name: '{{ PKGS_REDHAT_REMOVAL_LIST }}'
        state: absent
        allowerasing: true
        autoremove: true
      become: true

    - name: Update RedHat-based system
      dnf:
        name: '*'
        state: latest
        update_cache: true
        install_weak_deps: false
      become: true

    - name: Install EPEL release on RHEL-based system
      dnf:
        name: epel-release
        state: latest
        update_cache: true
        install_weak_deps: false
      when: ansible_distribution != "Fedora"
      become: true

    - name: Install necessary packages
      dnf:
        name: '{{ PKGS_REDHAT_INSTALLATION_LIST }}'
        state: latest
        update_cache: true
        install_weak_deps: false
      become: true

    - name: Autoremove unused pkgs
      dnf:
        autoremove: true
      become: true

  when: ansible_os_family == "RedHat"
