---
- name: Create groups and users
  block:
    - name: Create SFTP groups
      group:
        name: '{{ item.name }}'
        state: present
      loop: '{{ SFTP_GROUPS | default(omit) }}'
      become: true

    - name: Create SFTP users
      user:
        name: '{{ item.name }}'
        password: '{{ user_password_hashed | default(omit) }}'
        append: true
        shell: /usr/sbin/nologin
        groups: '{{ item.group | default(omit) }}'
        create_home: false
        state: present
      vars:
        user_password_hashed: "{{ item.password | password_hash('sha512') }}"
      loop: '{{ SFTP_USERS }}'
      no_log: true
      become: true

- name: Create directories
  block:
    - name: Get unique chroot directories
      set_fact:
        unique_chroots: "{{ SFTP_SHARES_LIST | map(attribute='chroot') | list | unique }}"

    - name: Create SFTP chroot directories
      file:
        path: '{{ item }}'
        state: directory
        recurse: true
        mode: 0755
        owner: root
        group: root
      loop: '{{ unique_chroots }}'
      become: true

    - name: Filter all users and groups
      set_fact:
        sftp_groups: "{{ SFTP_SHARES_LIST | selectattr('type', 'equalto', 'group') | list }}"
        sftp_users: "{{ SFTP_SHARES_LIST | selectattr('type', 'equalto', 'user') | list }}"

    - name: Create SFTP subdirectories for groups
      file:
        path: '{{ item.chroot }}/{{ item.subdir }}'
        state: directory
        recurse: true
        mode: '{{ item.mode }}'
        group: '{{ item.name }}'
      loop: '{{ sftp_groups }}'
      become: true

    - name: Create SFTP subdirectories for users
      file:
        path: '{{ item.chroot }}/{{ item.subdir }}'
        state: directory
        recurse: true
        mode: '{{ item.mode }}'
        owner: '{{ item.name }}'
      loop: '{{ sftp_users }}'
      become: true

- name: Apply SFTP config
  template:
    src: 05_sftp.conf.j2
    dest: /etc/ssh/sshd_config.d/05_sftp.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart sshd
  become: true
