---
- name: Check WireGuard config existence
  stat:
    path: '{{ WIREGUARD_CONFIG_PATH_SRC }}'
  delegate_to: localhost
  register: wg_config_existence

- name: Install and config WireGuard
  block:
    - name: Install WireGuard tools on Debian-based system
      apt:
        name: wireguard-tools
        state: latest
        update_cache: true
        install_recommends: false
      when: ansible_os_family == "Debian"

    - name: Install WireGuard tools on RHEL-based system
      dnf:
        name: wireguard-tools
        state: latest
        update_cache: true
        install_weak_deps: false
      when: ansible_os_family == "RedHat"

    - name: Apply config
      copy:
        src: '{{ WIREGUARD_CONFIG_PATH_SRC }}'
        dest: '{{ WIREGUARD_CONFIG_PATH_DEST }}'
        mode: 0400

    - name: Start WireGuard
      service:
        name: wg-quick@{{ WIREGUARD_CONFIG_NAME }}
        state: started
        enabled: true

  when: wg_config_existence.stat.exists
  become: true
